# Generated by Django 2.2.5 on 2021-08-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20210812_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qna',
            name='b_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tips',
            name='b_content',
            field=models.TextField(),
        ),
    ]
